#!/bin/bash
# Generate a .env with fresh secrets for the Aegis compose stack.
#
# The stack refuses to start without these (docker-compose.yml uses the
# ${VAR:?} form) and the application refuses to start on the shipped
# development defaults (backend/app/security_posture.py). A security product
# that ships with a known HMAC key is not a convenience, so there is no
# fallback: generate real values once, here.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$ROOT/.env"

if [ -e "$TARGET" ] && [ "${1:-}" != "--force" ]; then
  echo "$TARGET already exists. Re-run with --force to replace it." >&2
  exit 1
fi

# A URL-safe random secret. openssl ships with Git for Windows and every Linux;
# python3 is the last resort because on Windows `python3` is often the Microsoft
# Store stub, which prints nothing and exits 0 -- and an empty secret is exactly
# what the application then refuses to start on. So every value is checked.
gen() {
  local value=""
  if command -v openssl >/dev/null 2>&1; then
    value="$(openssl rand -base64 33 | tr '+/' '-_' | tr -d '=\n')"
  elif [ -r /dev/urandom ]; then
    value="$(head -c 33 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n')"
  elif command -v python3 >/dev/null 2>&1; then
    value="$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || true)"
  fi
  if [ "${#value}" -lt 32 ]; then
    echo "Could not generate a random secret (need openssl, /dev/urandom or python3)." >&2
    exit 1
  fi
  printf '%s' "$value"
}

cat > "$TARGET" <<ENV
# Generated by scripts/init-env.sh -- do not commit (.env is gitignored).
AEGIS_SECRET_KEY=$(gen)
AEGIS_EAT_KEY=$(gen)
AEGIS_EVIDENCE_SECRET_KEY=$(gen)
AEGIS_INTERNAL_GATEWAY_TOKEN=$(gen)
AEGIS_INTERNAL_TOOL_TOKEN=$(gen)
AEGIS_CRM_SECRET=$(gen)
# Identity of the runtime-verification agent that runs in the agent container.
# An ordinary agent token, enforced like any other.
AEGIS_VERIFY_AGENT_TOKEN=aegis_$(gen)
# Identity of the Phase 19 AI agent. Also an ordinary agent token: it is the
# only credential that container holds, and it grants nothing at Google.
AEGIS_GMAIL_AGENT_TOKEN=aegis_$(gen)
# Seals the Google refresh tokens at rest (backend/app/secretbox.py).
AEGIS_OAUTH_ENCRYPTION_KEY=$(gen)

# ---------------------------------------------------------------------------
# Phase 19 values a HUMAN must fill in. Left empty on purpose -- this script
# cannot create a Google OAuth client or buy model credits for you, and an
# invented value would produce a stack that looks configured and is not.
#
# Google OAuth client, from Google Cloud Console. See docs/PHASE_19_GMAIL.md
# for exactly which buttons to press.
AEGIS_GOOGLE_CLIENT_ID=
AEGIS_GOOGLE_CLIENT_SECRET=
AEGIS_GOOGLE_REDIRECT_URI=http://localhost:8000/api/gmail/oauth/callback
#
# The AI agent's model. Any OpenAI-compatible provider. The host below must
# also appear in AEGIS_EGRESS_ALLOWLIST or the agent cannot reach it.
AEGIS_AGENT_LLM_BASE_URL=https://api.deepseek.com/v1
AEGIS_AGENT_LLM_API_KEY=
AEGIS_AGENT_LLM_MODEL=deepseek-chat
#
# The complete list of hosts the agent container may reach. Adding a Google
# host here would defeat the Phase 19 network boundary; do not.
AEGIS_EGRESS_ALLOWLIST=api.deepseek.com
ENV

chmod 600 "$TARGET"
echo "Wrote $TARGET with fresh secrets."
